# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, max_length=255, null=True, upload_to=b'upload_file/users', verbose_name=b'Profile Picture')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female'), (3, b'Secret')], null=True)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
